### ISSUE TITLE
Heroku run rake

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/marketInspector#31]
rake aborted!
Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context at line 22 column 13
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/psych.rb:370:in `parse'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/psych.rb:370:in`parse_stream'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/psych.rb:318:in `parse'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/psych.rb:245:in`load'
/app/Rakefile:12:in `<top (required)>'

**Comment by n8rzz** [comment]
closed by f216a4faebdf763e2f47abde1ae7ed9fdbb7c440
